### ISSUE TITLE
Try Princeton's Docker Compose Setup

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express-starter#34]
https://hub.docker.com/r/wdsprinceton/princeton-sites/~/dockerfile/

```yaml
version: '2'

services:
  cms:
    image: wdsprinceton/princeton-sites
    container_name: cms
    mem_limit: 512M
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - .:/var/www/html/princeton:cached
      #- ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      - MYSQL_HOST=db
    networks:
      - connector

  db:
    image: mysql:5.6
    container_name: db
    mem_limit: 512M
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 33006:3306
    networks:
      - connector

networks:
  connector:
```

Those two resources might be useful if/when the docker branch is worked on.
